### ISSUE TITLE
when I trying to run Dynamic-Oozie-Workflow-Creator jar on ec2 instance then it will give me error

### ISSUE THREAD

**Issue by dineshjadhav-oi** [zandeeppb/Dynamic-Oozie-Workflow-Creator#2]
[ec2-user@ip-10-0-0-216 dinesh]$ hadoop jar DynamicOozieWorkflowCreator.jar com.oozie.DynWfGenerator
17/12/22 09:34:24 INFO wfmanger.WfManagerImpl: Create dynamic oozie workflow.XML and write to HDFS
17/12/22 09:34:25 INFO wfmanger.WfManagerImpl: context
javax.xml.bind.JAXBException
 - with linked exception:
[java.io.FileNotFoundException: file:/home/ec2-user/dinesh/sparkSample/workflow.xml (No such file or directory)]
        at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:108)
        at com.oozie.wfmanger.WfManagerImpl.generateWorkFlow(WfManagerImpl.java:52)
        at com.oozie.DynWfGenerator.main(DynWfGenerator.java:16)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:233)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:148)
Caused by: java.io.FileNotFoundException: file:/home/ec2-user/dinesh/sparkSample/workflow.xml (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at javax.xml.bind.helpers.AbstractMarshallerImpl.marshal(AbstractMarshallerImpl.java:101)
        ... 8 more

**Comment by zandeeppb** [comment]
Closing this issue as it is resolved
